
// column tags

const tags = [
  { find: /^4ku /i,          misc: "4k" },
  { find: /^alexandria /i,   lang: "C++", search: "PVS", eval: "NN" },
  { find: /^altair /i,       lang: "C++", eval: "NN", search: "PVS" },
  { find: /^arasan /i,       lang: "C++", search: "PVS", eval: "NN" },
  { find: /^astra /i,        lang: "C++", search: "PVS", eval: "NN" },
  { find: /^aquarii /i,      search: "MCTS" },
  { find: /^bagatur /i,      lang: "Java" },
  { find: /^berserk /i,      lang: "C", eval: "NN", search: "PVS" },
  { find: /^black marlin /i, lang: "Rust", eval: "NN", search: "PVS" },
  { find: /^blunder /i,      lang: "Go" },
  { find: /^booot /i,        eval: "NN", lang: "Pascal", search: "PVS" },
  { find: /^bread /i,        lang: "C++", eval: "NN", search: "PVS" },
  { find: /^c4ke /i,         misc: "4k" },
  { find: /^caissa /i,       lang: "C++", search: "PVS", eval: "NN" },
  { find: /^calvin /i,       lang: "Java", eval: "NN", search: "PVS" },
  { find: /^carballo /i,     lang: "Java" },
  { find: /^chess22k /i,     lang: "Java" },
  { find: /^chess-3 /i,      lang: "Go" },
  { find: /^chess4j /i,      lang: "Java", eval: "NN"},
  { find: /^chessnix /i,     lang: "Zig" },
  { find: /^cinder /i,       lang: "Rust", search: "PVS", eval: "NN" },
  { find: /^clarity /i,      eval: "NN", lang: "C++", search: "PVS" },
  { find: /^clockwork /i,    eval: "HCE", misc: "Collab" },
  { find: /^clover /i,       eval: "NN", lang: "C++", search: "PVS" },
  { find: /^cuckoochess /i,  lang: "Java" },
  { find: /^combusk/i,       lang: "Go" },
  { find: /^cwtch /i,        lang: "C", eval: "NN", search: "PVS" },
  { find: /^detroid /i,      lang: "Java" },
  { find: /^dirty catpaw /i, lang: "C++", eval: "HCE", search: "PVS" },
  { find: /^donna /i,        lang: "Go" },
  { find: /^dragon /i,       eval: "NN", misc: "Private" },
  { find: /^dragontooth /i,  lang: "Go" },
  { find: /^ethereal /i,     lang: "C", eval: "NN", search: "PVS" },
  { find: /^eques /i,        lang: "Go" },
  { find: /^eveann /i,       lang: "Pascal", eval: "NN", search: "PVS" },
  { find: /^frankygo/i,      lang: "Go" },
  { find: /^frankwalter/i,   lang: "Java" },
  { find: /^fritz /i,        eval: "NN", misc: "Private" },
  { find: /^gopherc/i,       lang: "Go" },
  { find: /^halogen /i,      eval: "NN", lang: "C++", search: "PVS" },
  { find: /^heimdall /i,     eval: "NN", lang: "Nim", search: "PVS" },
  { find: /^horsie /i,       lang: "C++", search: "PVS", eval: "NN" },
  { find: /^houdini /i,      misc: "Clone" },
  { find: /^igel /i,         lang: "C++", search: "PVS", eval: "NN" },
  { find: /^jackal /i,       search: "MCTS" },
  { find: /^jacky/i,         lang: "Java" },
  { find: /^khepri/i,        lang: "JS", eval: "HCE" },
  { find: /^koivisto /i,     eval: "NN", lang: "C++", search: "PVS" },
  { find: /^ice /i,          eval: "HCE" },
  { find: /^ice4 /i,         misc: "4k" },
  { find: /^integral /i,     lang: "C++", search: "PVS", eval: "NN" },
  { find: /^lambergar /i,    lang: "Zig" },
  { find: /^leorik /i,       lang: "C#", eval: "NN", search: "PVS" },
  { find: /^lizard /i,       eval: "NN", lang: "C#", search: "PVS" },
  { find: /^lozza /i,        lang: "JS", eval: "NN", search: "PVS" },
  { find: /^lynx /i,         eval: "HCE" },
  { find: /^maels/i,         lang: "Go" },
  { find: /^mess /i,         lang: "Go" },
  { find: /^minic /i,        eval: "NN", lang: "C++", search: "PVS" },
  { find: /^monty /i,        search: "MCTS" },
  { find: /^motor /i,        lang: "C++", search: "PVS", eval: "NN" },
  { find: /^nalwald /i,      eval: "HCE" },
  { find: /^nemorino /i,     lang: "C++", eval: "NN", search: "PVS" },
  { find: /^obsidian /i,     lang: "C++", search: "PVS", eval: "NN" },
  { find: /^olithink /i,     lang: "Java" },
  { find: /^pawnocchio /i,   eval: "NN", lang: "Zig", search: "PVS" },
  { find: /^peacekeeper /i,  eval: "NN", lang: "C++", search: "PVS" },
  { find: /^perseus /i,      eval: "HCE" },
  { find: /^pirarucu /i,     lang: "Java" },
  { find: /^plentychess /i,  lang: "C++", search: "PVS", eval: "NN" },
  { find: /^princhess /i,    search: "MCTS" },
  { find: /^protej /i,       eval: "HCE" },
  { find: /^radiance /i,     lang: "Zig" },
  { find: /^reckless /i,     lang: "Rust", search: "PVS", eval: "NN", misc: "Collab" },
  { find: /^renegade /i,     eval: "NN", lang: "C++", search: "PVS" },
  { find: /^rofchade /i,     eval: "NN", lang: "C++", search: "PVS" },
  { find: /^quanti/i,        lang: "C", eval: "NN", search: "PVS" },
  { find: /^rubichess /i,    lang: "C++", search: "PVS", eval: "NN" },
  { find: /^seer /i,         eval: "NN", lang: "C++", search: "PVS" },
  { find: /^serendipity /i,  lang: "Java" },
  { find: /^senpai /i,       eval: "HCE" },
  { find: /^sirius /i,       lang: "C++", eval: "HCE", search: "PVS" },
  { find: /^starzix /i,      eval: "NN", lang: "C++", search: "PVS" },
  { find: /^stash /i,        eval: "HCE" },
  { find: /^stockfish /i,    lang: "C++", search: "PVS", eval: "NN", misc: "Collab" },
  { find: /^stormphrax /i,   lang: "C++", search: "PVS", eval: "NN" },
  { find: /^stro4k /i,       misc: "4k" },
  { find: /^superultra /i,   lang: "C++", eval: "NN", search: "PVS" },
  { find: /^tarnished /i,    eval: "NN", lang: "C++", search: "PVS" },
  { find: /^titan /i,        lang: "Rust", search: "PVS", eval: "NN" },
  { find: /^tomitank/i,      lang: "JS", eval: "HCE"},
  { find: /^torch /i,        eval: "NN", misc: "Private" },
  { find: /^uralochka /i,    lang: "C++", search: "PVS", eval: "NN" },
  { find: /^velvet /i,       lang: "Rust", search: "PVS", eval: "NN" },
  { find: /^victorie /i,     lang: "Zig" },
  { find: /^viridithas /i,   lang: "Rust", search: "PVS", eval: "NN" },
  { find: /^vine /i,         search: "MCTS" },
  { find: /^wasp /i,         lang: "C" },
  { find: /^weasel /i,       lang: "Go" },
  { find: /^weiss /i,        eval: "HCE" },
  { find: /^willow /i,       lang: "C++", eval: "NN", search: "PVS" },
  { find: /^wukong/i,        lang: "JS", eval: "HCE" },
  { find: /^yukari /i,       lang: "Rust", eval: "NN", search: "PVS" },
  { find: /^zahak /i,        lang: "Go" },
  { find: /^zurichess /i,    lang: "Go" },
];

export function getEngineTags(engine) {
  const s = engine.toLowerCase();
  return tags
    .filter(t => t.find.test(s))
    .map(({ find, ...rest }) => rest);
}

export function getAllTagKeys() {
  const set = new Set();
  for (const entry of tags) {
    for (const key of Object.keys(entry)) {
      if (key !== "find") set.add(key);
    }
  }
  return set;
}

